### ISSUE TITLE
File Settings path missing starting slash issue

### ISSUE THREAD

**Issue by lilyana-boneva-icb** [crowdin/ota-client-js#34]
Привет,

We have an Angular application  and а Crowdin project we want to use for translations ( Project ID: 486605). We use JSON files and have translations in 3 languages: Finnish, French and Swedish.  Our initial setup is with CDN integration. We have created a distribution pointing to our source translations in English (en.ts). We have uploaded our current translations and made distribution release and build the project.
We installed the ota-client library and we got empty strings for our translation. Here is detailed description:

**Case 1:** When file setting for the source content file en.ts was missing leading slash: **development/%two_letters_code%.ts**:
**ota-client Library Behaviour**: CDN files were created in 3 different folders for the 3 locales rather then in the development folder, e.g.
https://distributions.crowdin.net/8bd5fd98d64a79388c828a8g2b9/content/fr/development/fr.ts?timestamp=1643978136
https://distributions.crowdin.net/8bd5fd98d64a79388c828a8g2b9/content/fi/development/fi.ts?timestamp=1643978136
https://distributions.crowdin.net/8bd5fd98d64a79388c828a8g2b9/content/sv-SE/development/sv.ts?timestamp=1643978136

As a result I could not get any strings from the ota-client calling methods getStrings() which returned the 3 locales with empty content and getLanguageTranslations("fi") was returning an error. The distribution manifest file was:
"files": [
        "development/%two_letters_code%.ts"
    ],

**Case 2**: Support suggested using File setting path: **development/en.ts**.  Again 3 different folders were created but all files were named en.ts, e.g.:
https://distributions.crowdin.net/<distribution_hash>/content/fr/development/en.ts?timestamp=<some_timestamp>
**ota-client Library Behaviour***: The distribution manifest file was:
"files": [
        "development/en.ts"
    ],
Method client.getStrings() still returned empty objects for the 3 locales. Method client..getLanguageTranslations('fr') returned values for the specified locale. 
This was not optimal because we need also to download the files and having them all named correctly.

**Case 3**: Then I decided that path might be expected with starting slash. Changing path to **/development/%two_letters_code%.ts** generated expected file structure in CDN - now all 3 files are in one folder:
https://distributions.crowdin.net/8bd5fd98d64a79388c828a8g2b9/content/development/fi.ts?timestamp=1644326939
https://distributions.crowdin.net/8bd5fd98d64a79388c828a8g2b9/content/development/fr.ts?timestamp=1644326939
https://distributions.crowdin.net/8bd5fd98d64a79388c828a8g2b9/content/development/sv.ts?timestamp=1644326939
**ota-client Library Behaviour***: Method client.getStrings() still returns empty objects for the 3 locales. Method client..getLanguageTranslations('fr') returns values for the specified locale. 

**Expected behaviour**:  Method getStrings() returns values for the 3 locales.
We also expected to get error or some insight that File Setting path was wrong.
Your response is highly appreciated.

С уважением,
Лиляна

**Comment by ImRodry** [comment]
Hey! I tried to replicate this behavior with your distribution hash and I could not reproduce it.
This is what your manifest file looks like at the moment of me writing this, which, as you can see, does have the leading slash:
![image](https://user-images.githubusercontent.com/38259440/153305942-d53ed7f0-0cd3-49a1-aec0-017c8052086d.png)
And, upon fetching it on the client, I get the same thing as expected:
![image](https://user-images.githubusercontent.com/38259440/153305973-ce090ab5-fc7a-4798-a50d-64a13e58d8c1.png)

The reason you aren't getting any strings from the getStrings() method is that this only works with **json** files, as noted in the JSDoc comment. Since you're using a typescript file, the contents provided by the CDN come in the form of a string, not an object, which doesn't let the client parse strings from it, and thus returns an empty object for all languages, as expected.

Now, the getLanguageTranslations() works differently, as it simply outputs the result given by the CDN, which, in your case, is a string of TS code, so it will work as expected as no transformation needs to be done. What I recommend doing is iterating through your manifest languages and fetch the translations using this method for each language, then map them to an array and do whatever you need to do with them. Alternatively, if you want the parsed strings, you will have to change the files in your project to the **json** format.

I may have misunderstood some parts of your issue so please let me know if I missed anything, but this is what it looks like to me at a glance and after some testing!

**Comment by lilyana-boneva-icb** [comment]
Thanks for the fast reply! I also tried to reproduce - changing the settings without the leading slash but now it works. Thanks for the clarification on getStrings() method - I probably missed this in the documentation.

**Comment by andrii-bodnar** [comment]
@ImRodry thanks for the help! 

We are going to add some exception handling for this case.
