### ISSUE TITLE
Dont' work on Node.JS

### ISSUE THREAD

**Issue by ferreiro** [crowdin/ota-client-js#5]
Hey guys! Great work. Olga shared the SDK and I'm trying to test it out.

I'm very interested to pull the files from our backend so we can hydrate our frontend with the initial translations. Is there any way your SDK could work for Node?

I got this:
<img width="779" alt="Screen Shot 2020-12-18 at 9 28 45 AM" src="https://user-images.githubusercontent.com/7242959/102592215-70590b80-4113-11eb-85f9-d6a116e32394.png">

**Comment by yevheniyJ** [comment]
@ferreiro hi there! Could you please share the part of code with the import/require statement? And also would be nice to know which version of the library you are using. Thanks!

**Comment by yevheniyJ** [comment]
It looks to me that problem is not in Node itself but rather in wrong import of `OtaClient`

**Comment by ferreiro** [comment]
hey @yevheniyJ sorry for the delay :/ I've tried several things:

```js
const otaClient = require('@crowdin/ota-client');

console.log(otaClient);
const hash = '{distribution_hash}';
const client = new otaClient(hash);

// get list of files in distribution
client
 	.listFiles()
 	.then(files => console.log(file))
 	.catch(error => console.error(error));
```

```js
const {otaClient} = require('@crowdin/ota-client');

console.log(otaClient);
const client = new otaClient('{distribution_hash}');

// get list of files in distribution
client
 	.listFiles()
 	.then(files => console.log(file))
 	.catch(error => console.error(error));
```

both of them produced the same error...

However, I figured out how to make it work...

```
const otaClient = require('@crowdin/ota-client');
const client = new otaClient.default('{distribution_hash}');
```

so I needed to use `otaClient.default`, so the instructions in the readme are wrong. Can you update this to work for this:

```
const otaClient = require('@crowdin/ota-client');
const client = new otaClient.default(hash);
```

**Comment by yevheniyJ** [comment]
@ferreiro hi hi!) good that you found the solution. I suggest to move `default` suffix  to the require section. So in the end you should have smth like this : `const otaClient = require(“@crowdin/ota-client”).default;` and later on create an instance without `default` keyword. In my eyes it is more understandable 🙂

**Comment by yevheniyJ** [comment]
And in readme we are using ES6 import/export syntax and it is correct. I will just add another example with  Node.js`require` option.

**Comment by Garbee** [comment]
Just in case anyone else hits this. I am using Node v14.18.2 with the mjs extension to use ES6 imports. The examples all show `import otaClient from '@crowdin/ota-client';` however upon trying to create a new object it failed since this does not make otaClient a constructor. I instead had to end up doing `const client = new otaClient.default(hash);`.

Upon logging, you will see the default example creating an object with the default property containing the constructor. The import rename syntax also does *NOT* work here, `import {default as otaClient} from '@crowdin/ota-client';`. This still makes otaClient the object with a default property.

Could be a bug in Node or a general issue with packaging modules. Just a note here in case anyone else comes across this with es6 module imports too.
